language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --omit=*site-packages/*  -m unittest discover tests -t /
after_success: coveralls
