#!/bin/bash

journey_times() {
    python update_journey_times.py /app/data/ccdb.sqlite -k $GMAPS_API_KEY;
}

season_tickets() {
    python update_season_tickets.py /app/data/ccdb.sqlite;
}

if [[ $1 =~ ^(journey_times|season_tickets)$ ]]; then
    COMMAND=$1
    shift
    $COMMAND "$@"
else
    echo "Command not recognised: $1"
    exit 1
fi
